Remove m2crypto from "install" lines for dnf-plugin-spacewalk
m2crypto was never a requirement for dnf-plugin-spacewalk,
only yum-rhn-plugin requires it.

What is more, m2crypto is not available on CentOS 8:

  # dnf -y install rhn-client-tools rhn-check rhn-setup rhnsd m2crypto dnf-plugin-spacewalk
  Package rhn-client-tools-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 is already installed.
  Package rhn-check-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 is already installed.
  Package rhn-setup-2.8.16-13.module_el8.1.0+211+ad6c0bc7.x86_64 is already installed.
  Package rhnsd-5.0.35-3.module_el8.1.0+211+ad6c0bc7.x86_64 is already installed.
  No match for argument: m2crypto
  Package dnf-plugin-spacewalk-2.8.5-11.module_el8.1.0+211+ad6c0bc7.noarch is already installed.
  Error: Unable to find a match: m2crypto